export const SUGAR_TERMS = [
    "sugar",
    "added sugar",
    "cane sugar",
    "cane juice",
    "evaporated cane juice",
    "corn syrup",
    "high fructose corn syrup",
    "hfcs",
    "glucose syrup",
    "fructose",
    "dextrose",
    "maltodextrin",
    "invert sugar",
    "brown rice syrup",
    "rice syrup",
    "barley malt",
    "malt syrup",
    "malt",
    "molasses",
    "honey",
    "agave",
    "maple syrup",
    "caramel",
    "fruit juice concentrate",
    "concentrated fruit juice",
    "sucrose",
    "glucose",
    "lactose",
    "maltose",
    "trehalose"
];
